-- Deletar todas as tabelas
DROP TABLE IF EXISTS AGENDAMENTO_DOACAO;
DROP TABLE IF EXISTS BANCO_SANGUE;
DROP TABLE IF EXISTS ESPECIALIDADE_HEMOCENTRO;
DROP TABLE IF EXISTS CONSULTA;
DROP TABLE IF EXISTS ESPECIALIDADE;
DROP TABLE IF EXISTS DOADOR;
DROP TABLE IF EXISTS HEMOCENTRO;
DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS TIPO_SANGUINEO;

-- Criar tabelas
CREATE TABLE TIPO_SANGUINEO (
    ID_TIPO_SANGUINEO INT NOT NULL AUTO_INCREMENT,
    TIPO_SANGUE VARCHAR(50) NOT NULL,
    FATOR_RH VARCHAR(5) NOT NULL,
    PRIMARY KEY (ID_TIPO_SANGUINEO)
);

CREATE TABLE ENDERECO (
    ID_ENDERECO INT NOT NULL AUTO_INCREMENT,
    LONGRADOURO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    LATITUDE VARCHAR(20) NOT NULL,
    LONGITUDE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_ENDERECO)
);

CREATE TABLE HEMOCENTRO (
    ID_HEMOCENTRO INT NOT NULL AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    CPNJ VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    PRIMARY KEY (ID_HEMOCENTRO)
);

CREATE TABLE DOADOR (
    ID_DOADOR INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ID_ENDERECO INT NOT NULL,
    PESO VARCHAR(10) NOT NULL,
    QUANTIDADE_DOACOES VARCHAR(10) NOT NULL,
    ID_TIPO_SANGUINEO INT NOT NULL,
    PRIMARY KEY (ID_DOADOR)
);

CREATE TABLE ESPECIALIDADE (
    ID_ESPECIALIDADE INT NOT NULL AUTO_INCREMENT,
    NOME_ESPECIALIDADE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_ESPECIALIDADE)
);

CREATE TABLE CONSULTA (
    ID_CONSULTA INT NOT NULL AUTO_INCREMENT,
    DATA_CONSULTA DATE NOT NULL,
    VALOR_CREDITO VARCHAR(10) NOT NULL,
    ID_DOADOR INT NOT NULL,
    ID_ESPECIALIDADE INT NOT NULL,
    ID_HEMOCENTRO INT NOT NULL,
    PRIMARY KEY (ID_CONSULTA)
);

CREATE TABLE ESPECIALIDADE_HEMOCENTRO (
    ID_ESPECIALIDADE INT NOT NULL,
    ID_HEMOCENTRO INT NOT NULL,
    PRIMARY KEY (ID_ESPECIALIDADE, ID_HEMOCENTRO)
);

CREATE TABLE BANCO_SANGUE (
    ID_BANCO_SANGUE INT NOT NULL AUTO_INCREMENT,
    ID_TIPO_SANGUINEO INT NOT NULL,
    ID_HEMOCENTRO INT NOT NULL,
    QUANTIDADE_DISPONIVEL NUMERIC NOT NULL,
    PRIMARY KEY (ID_BANCO_SANGUE)
);

CREATE TABLE AGENDAMENTO_DOACAO (
    ID_AGENDAMENTO_DOACOES INT NOT NULL AUTO_INCREMENT,
    DATA_AGENDAMENTO DATE NOT NULL,
    HORA_AGENDAMENTO TIME NOT NULL,
    ID_DOADOR INT NOT NULL,
    ID_HEMOCENTRO INT NOT NULL,
    STATUS_AGEND VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_AGENDAMENTO_DOACOES)
);

-- Adicionar as restrições de chave estrangeira
ALTER TABLE BANCO_SANGUE ADD CONSTRAINT tipo_sanguineo_banco_sangue_fk
FOREIGN KEY (ID_TIPO_SANGUINEO)
REFERENCES TIPO_SANGUINEO (ID_TIPO_SANGUINEO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DOADOR ADD CONSTRAINT tipo_sanguineo_doador_fk
FOREIGN KEY (ID_TIPO_SANGUINEO)
REFERENCES TIPO_SANGUINEO (ID_TIPO_SANGUINEO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DOADOR ADD CONSTRAINT endereco_beneficiario_fk
FOREIGN KEY (ID_ENDERECO)
REFERENCES ENDERECO (ID_ENDERECO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE HEMOCENTRO ADD CONSTRAINT endereco_prestador_fk
FOREIGN KEY (ID_ENDERECO)
REFERENCES ENDERECO (ID_ENDERECO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE AGENDAMENTO_DOACAO ADD CONSTRAINT prestador_agendamentos_fk
FOREIGN KEY (ID_HEMOCENTRO)
REFERENCES HEMOCENTRO (ID_HEMOCENTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ESPECIALIDADE_HEMOCENTRO ADD CONSTRAINT prestador_especialidades_prestador_fk
FOREIGN KEY (ID_HEMOCENTRO)
REFERENCES HEMOCENTRO (ID_HEMOCENTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE BANCO_SANGUE ADD CONSTRAINT prestador_banco_sangue_fk
FOREIGN KEY (ID_HEMOCENTRO)
REFERENCES HEMOCENTRO (ID_HEMOCENTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CONSULTA ADD CONSTRAINT prestador_consultas_fk
FOREIGN KEY (ID_HEMOCENTRO)
REFERENCES HEMOCENTRO (ID_HEMOCENTRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE AGENDAMENTO_DOACAO ADD CONSTRAINT beneficiario_agendamentos_fk
FOREIGN KEY (ID_DOADOR)
REFERENCES DOADOR (ID_DOADOR)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CONSULTA ADD CONSTRAINT doador_consultas_fk
FOREIGN KEY (ID_DOADOR)
REFERENCES DOADOR (ID_DOADOR)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ESPECIALIDADE_HEMOCENTRO ADD CONSTRAINT especialidades_especialidades_prestador_fk
FOREIGN KEY (ID_ESPECIALIDADE)
REFERENCES ESPECIALIDADE (ID_ESPECIALIDADE)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CONSULTA ADD CONSTRAINT especialidade_consultas_fk
FOREIGN KEY (ID_ESPECIALIDADE)
REFERENCES ESPECIALIDADE (ID_ESPECIALIDADE)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
