CREATE TABLE ENDERECO (
    ID_ENDERECO INT NOT NULL AUTO_INCREMENT,
    LOGRADOURO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    PRIMARY KEY (ID_ENDERECO)
);

CREATE TABLE BENEFICIARIO (
    ID_BENEFICIARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    TIPO_SANGUINEO VARCHAR(3) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ID_ENDERECO INT NOT NULL,
    QUANTIDADE_DOADA NUMERIC NOT NULL,
    PRIMARY KEY (ID_BENEFICIARIO)
);

CREATE TABLE ESPECIALIDADES (
    ID_ESPECIALIDADE INT NOT NULL AUTO_INCREMENT,
    NOME_ESPECIALIDADE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_ESPECIALIDADE)
);

CREATE TABLE BANCO_SANGUE (
    ID_BANCO_SANGUE INT NOT NULL AUTO_INCREMENT,
    TIPO_SANGUINEO VARCHAR(3) NOT NULL,
    FATOR_RH VARCHAR(3) NOT NULL,
    QUANTIDADE_DISPONIVEL NUMERIC NOT NULL,
    PRIMARY KEY (ID_BANCO_SANGUE)
);

CREATE TABLE PRESTADOR (
    ID_PRESTADOR INT NOT NULL AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    ID_BANCO_SANGUE INT NOT NULL,
    PRIMARY KEY (ID_PRESTADOR)
);

CREATE TABLE ESPECIALIDADES_PRESTADOR (
    ID_ESPECIALIDADE INT NOT NULL,
    ID_PRESTADOR INT NOT NULL,
    PRIMARY KEY (ID_ESPECIALIDADE, ID_PRESTADOR)
);

CREATE TABLE AGENDAMENTOS (
    ID_AGENDAMENTO INT NOT NULL AUTO_INCREMENT,
    DATA_AGENDAMENTO DATE NOT NULL,
    HORA_AGENDAMENTO TIME NOT NULL,
    TIPO_AGENDAMENTO CHAR(10) NOT NULL,
    ID_BENEFICIARIO INT NOT NULL,
    ID_PRESTADOR INT NOT NULL,
    PRIMARY KEY (ID_AGENDAMENTO)
);

-- Foreign Key Constraints

ALTER TABLE BENEFICIARIO ADD CONSTRAINT endereco_beneficiario_fk
FOREIGN KEY (ID_ENDERECO)
REFERENCES ENDERECO (ID_ENDERECO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PRESTADOR ADD CONSTRAINT endereco_prestador_fk
FOREIGN KEY (ID_ENDERECO)
REFERENCES ENDERECO (ID_ENDERECO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE AGENDAMENTOS ADD CONSTRAINT beneficiario_agendamentos_fk
FOREIGN KEY (ID_BENEFICIARIO)
REFERENCES BENEFICIARIO (ID_BENEFICIARIO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE AGENDAMENTOS ADD CONSTRAINT prestador_agendamentos_fk
FOREIGN KEY (ID_PRESTADOR)
REFERENCES PRESTADOR (ID_PRESTADOR)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ESPECIALIDADES_PRESTADOR ADD CONSTRAINT especialidades_especialidades_prestador_fk
FOREIGN KEY (ID_ESPECIALIDADE)
REFERENCES ESPECIALIDADES (ID_ESPECIALIDADE)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ESPECIALIDADES_PRESTADOR ADD CONSTRAINT prestador_especialidades_prestador_fk
FOREIGN KEY (ID_PRESTADOR)
REFERENCES PRESTADOR (ID_PRESTADOR)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PRESTADOR ADD CONSTRAINT banco_sangue_prestador_fk
FOREIGN KEY (ID_BANCO_SANGUE)
REFERENCES BANCO_SANGUE (ID_BANCO_SANGUE)
ON DELETE NO ACTION
ON UPDATE NO ACTION;