CREATE VIEW HistoricoPacientes AS
SELECT 
    p.NOME AS NomePaciente, 
    h.RAZAO_SOCIAL AS NomeHospital, 
    his.DATA_CONSULTA, 
    his.OBSERVACAO
FROM 
    HISTORICO his
JOIN 
    PACIENTE p ON his.ID_PACIENTE = p.ID_PACIENTE
JOIN 
    HOSPITAL h ON his.ID_HOSPITAL = h.ID_HOSPITAL;