CREATE VIEW MedicosPorEspecialidade AS
SELECT 
    e.NOME_ESPECIALIDADE, 
    m.NOME AS NomeMedico, 
    m.CONSELHO
FROM 
    ESPECIALIDADE_MEDICO em
JOIN 
    ESPECIALIDADE e ON em.ID_ESPECIALIDADE = e.ID_ESPECIALIDADE
JOIN 
    MEDICO m ON em.ID_MEDICO = m.ID_MEDICO;