SELECT ID_HOSPITAL,
       RAZAO_SOCIAL,
       CNPJ,
       CATEGORIA,
       TELEFONE,
       EMAIL,
       LOGRADOURO,
       BAIRRO,
       CIDADE,
       e.ID_ENDERECO
FROM hospital AS h
INNER JOIN ENDERECO AS e ON h.ID_ENDERECO = e.ID_ENDERECO