SELECT m.ID_MEDICO, NOME, es.ID_ESPECIALIDADE, NOME_ESPECIALIDADE
FROM
    especialidade_medico AS esm
    INNER JOIN MEDICO AS m ON m.ID_MEDICO = esm.ID_MEDICO
    INNER JOIN ESPECIALIDADE AS es ON es.ID_ESPECIALIDADE = esm.ID_ESPECIALIDADE
ORDER BY NOME_ESPECIALIDADE