
SELECT NOME,
       CONSELHO,
       RAZAO_SOCIAL,
       CATEGORIA,
       NOME_ESPECIALIDADE
FROM hospital_medico AS hm
INNER JOIN MEDICO AS m ON m.ID_MEDICO = hm.ID_MEDICO
INNER JOIN HOSPITAL AS es ON es.ID_HOSPITAL = hm.ID_HOSPITAL
INNER JOIN ESPECIALIDADE AS esp ON esp.ID_ESPECIALIDADE = m.ID_MEDICO