SELECT ID_PACIENTE,
       NOME,
       CPF,
       TELEFONE,
       EMAIL,
       DATA_NASCIMENTO,
       LOGRADOURO,
       BAIRRO,
       CIDADE,
       e.ID_ENDERECO
FROM paciente AS p
INNER JOIN ENDERECO AS e ON p.ID_ENDERECO = e.ID_ENDERECO