SELECT es.ID_ESPECIALIDADE, es.NOME_ESPECIALIDADE, COUNT(m.ID_MEDICO) AS QUANTIDADE_MEDICOS
FROM
    especialidade_medico AS esm
    INNER JOIN MEDICO AS m ON m.ID_MEDICO = esm.ID_MEDICO
    INNER JOIN ESPECIALIDADE AS es ON es.ID_ESPECIALIDADE = esm.ID_ESPECIALIDADE
GROUP BY es.ID_ESPECIALIDADE, es.NOME_ESPECIALIDADE
ORDER BY es.NOME_ESPECIALIDADE;
