
SELECT NOME,
       NOME_ESPECIALIDADE
FROM especialidade_medico AS esm
INNER JOIN MEDICO AS m ON m.ID_MEDICO = esm.ID_MEDICO
INNER JOIN ESPECIALIDADE AS es ON es.ID_ESPECIALIDADE = esm.ID_ESPECIALIDADE