SELECT 
    h.DATA_CONSULTA,
    h.ID_HISTORICO,
    h.OBSERVACAO,
    ho.RAZAO_SOCIAL,
    ho.CATEGORIA,
    p.NOME AS NOME_PACIENTE,
    p.DATA_NASCIMENTO,
    m.NOME AS NOME_MEDICO,
    e.NOME_ESPECIALIDADE,
    h.ID_HOSPITAL,
    h.ID_PACIENTE,
    h.ID_MEDICO,
    h.ID_ESPECIALIDADE
FROM HISTORICO h
INNER JOIN PACIENTE p ON h.ID_PACIENTE = p.ID_PACIENTE
INNER JOIN HOSPITAL ho ON h.ID_HOSPITAL = ho.ID_HOSPITAL
INNER JOIN HOSPITAL_MEDICO hm ON ho.ID_HOSPITAL = hm.ID_HOSPITAL
INNER JOIN MEDICO m ON hm.ID_MEDICO = m.ID_MEDICO
INNER JOIN ESPECIALIDADE_MEDICO em ON m.ID_MEDICO = em.ID_MEDICO
INNER JOIN ESPECIALIDADE e ON em.ID_ESPECIALIDADE = e.ID_ESPECIALIDADE;
